### ISSUE TITLE
PGGAN for MNIST

### ISSUE THREAD

**Issue by Siriusblack1914** [Avhirup/PGGAN#1]
Hi,
could you explain/ give more details on using the code for MNIST dataset?

**Comment by avhirupc** [comment]
In the Generator & Disc class, i have a function called init_data which is meant to assign data. PGGAN class has objects of both G and D. so either you could hardcode data like i did in the Discriminator class, or you could modify to accept dataset during initialisation. The PGGAN has a method train to train the model. I have skipped the test and saving model part.They are pretty easy to figure out though

**Comment by avhirupc** [comment]
Most of the code lies in Network.py check that out
